## 数据处理

##### 1. N维数组（是机器学习和神经网络的主要数据结构  ）

   0-d（标量）# 一个类别  
   1-d（向量）# 一个特征向量  
   2-d（矩阵）# 一个样本-特征矩阵  
   3-d（图片）# RGB图片  
   4-d（批量）# 一个RGB图片批量  
   5-d（视频）# 一个视频批量

##### 2. 创建数组

1.创建数组需要：    
    形状：例如3×4矩阵  
    每个元素数据类型：例如32位浮点数  
    每个元素的值：例如全为0、特定值或随机数（正态分布/随机分布）  

##### 3. 访问元素

一个元素：[1,2]  #指矩阵中第2行第3列的元素 （#数组中行数列数从0开始  ）  
一行元素：[1,:]  #指数组中第2行所有元素  
一列元素：[:,1]  #指数组中第2列所有元素  
一个子域：[1:3,1:]  #第1行开始到第3行开区间结束（取第1、2行），第1列到之后所有元素   
步长区域：[::3,::2]  #从第0列开始每三行取一个元素、从第0列开始每2列取一个元素  

In [2]:
import torch

张量表示一个数值组成的数组这个数组可能有多个维度

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性来访问张量的形状和张量中的元素总数

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋确定值

In [9]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [10]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]]).shape

torch.Size([3, 4])

In [11]:
torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

表示1层3×4的矩阵  
或理解为一层1个、二层3个、三层4个

In [12]:
torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]).shape

torch.Size([1, 3, 4])

常见标准运算符都可以升级为元素运算（+ - * / **）

In [13]:
x = torch.tensor([1.0,2,4,8])  #1.0表示浮点运算，若改为1则为整形运算
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x**y  #**为求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素方式应用更多运算

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

也可以将多个张量拼接在一起

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(Y)
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
#把X、Y在第1维合并在一起,把元素在第0维合并在一起

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过**逻辑运算符**构建二元张量

In [16]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
X.sum()

tensor(66.)

即使数组形状不同，我们仍然可以通过调用**广播机制**（broadcasting mechanism）来执行元素操作

In [18]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
X[-1], X[1:3]  #将X的倒数第1行访问出来，将X的第行到第3行之间元素访问出来

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，还可以通过指定索引来将元素写入矩阵。

In [21]:
X[1,2] = 9  #将第1行第2列的元素改写为9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋相同的值，只需索引所有元素，然后为他们赋值。

In [22]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存
>若对很大的矩阵，一直复制可能导致内存问题

In [23]:
before = id(Y)  #id类似C++中指针，表示Y在Python中的地址
Y = X + Y  
id(Y) == before  #判断Y是否为之前的id

False

执行原地操作

In [24]:
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X + Y  
print("id(Z):",id(Z))

id(Z): 1898372489024
id(Z): 1898372489024


如果在后续计算中没有重复使用X，我们可以使用X[:] = X + Y 或X += Y 来减少操作内存的开销

In [25]:
before = id(X)
X += Y
id(X) == before

True

转换为NumPy张量

In [26]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量

In [27]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##### 数据预处理

创建一个人工数据集，并且储存在**csv**（逗号分隔值）文件

In [28]:
import os

os.makedirs(os.path.join('··', 'data'), exist_ok=True)
data_file = os.path.join('··', 'data', 'house_tiny.csv')  #创建一个文件夹，文件名为house.csv文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Prince\n')  #列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [29]:
import pandas as pd 
data = pd.read_csv(data_file)
data

NumRooms Alley  Prince
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

为了处理缺失数据，典型方法包括**插值**和**删除**，这里我们将考虑插值

In [35]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]  #对于data(4×3的表)通过iloc(indexlocation)把第0列、第1列和所有的行拿出来放到inputs里面，把最后一列拿出来放到outputs里面
inputs = inputs.fillna(inputs.mean())  #对于data中所有是na(Not a Number)的域，填一个值mean()  *mean()返回数组平均值
inputs
#print(inputs)

C:\Users\孙宇成\AppData\Local\Temp\ipykernel_6324\342642481.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())  #对于data中所有是na(Not a Number)的域，填一个值mean()  *mean()返回数组平均值


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

对于inputs中的类别值或者离散值，我们将"NaN"视为一个类别

In [36]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs
#print(inputs)

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

现在inputs和outputs中所有条目都是数值类型，它们可以转换为张量格式。

In [37]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)  #X取inputs中的值，y取outputs中的值
X, y 

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [47]:
X.size(),y.size()  #查看数组形状

(torch.Size([4, 3]), torch.Size([4]))